-- Whole database schema of the Contractor app.
-- Update this file in the same change that needs a new table or column,
-- then apply the change to the dev database by hand (see specs/tech-stack.md).
-- Tests rebuild their database from this file on every run.

CREATE TABLE branches (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255)
);

-- Employees for now. client_id comes with the clients table (roadmap step 6).
CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255) NOT NULL UNIQUE,
    password     VARCHAR(255) NOT NULL,
    role         VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'OFFICE', 'SERVICER', 'CLIENT')),
    display_name VARCHAR(255) NOT NULL,
    branch_id    BIGINT REFERENCES branches (id),
    -- false = deactivated: can't log in, rows that point to the user stay as they are
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);
