-- Whole database schema of the Contractor app.
-- Update this file in the same change that needs a new table or column,
-- then apply the change to the dev database by hand (see specs/tech-stack.md).
-- Tests rebuild their database from this file on every run.

CREATE TABLE branches (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255)
);
