-- Whole database schema of the Contractor app.
-- Update this file in the same change that needs a new table or column,
-- then apply the change to the dev database by hand (see specs/tech-stack.md).
-- Tests rebuild their database from this file on every run.

CREATE TABLE branches (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255)
);

CREATE TABLE clients (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           VARCHAR(20)  NOT NULL CHECK (type IN ('COMPANY', 'INDIVIDUAL')),
    name           VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone          VARCHAR(255),
    email          VARCHAR(255),
    -- Billing address, printed on the invoice. Work sites are in locations.
    address        VARCHAR(255)
);

-- Work sites of a client. Deleted together with the client (JPA cascade on Client.locations).
CREATE TABLE locations (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT       NOT NULL REFERENCES clients (id),
    name      VARCHAR(255),
    address   VARCHAR(255) NOT NULL,
    city      VARCHAR(255) NOT NULL
);

-- Employees and client users. Which role has a branch or a client is checked in UserService.
CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255) NOT NULL UNIQUE,
    password     VARCHAR(255) NOT NULL,
    role         VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'OFFICE', 'SERVICER', 'CLIENT')),
    display_name VARCHAR(255) NOT NULL,
    branch_id    BIGINT REFERENCES branches (id),
    client_id    BIGINT REFERENCES clients (id),
    -- false = deactivated: can't log in, rows that point to the user stay as they are
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Which order status can follow which. One row = one allowed change.
CREATE TABLE status_transitions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_status VARCHAR(20) NOT NULL CHECK (from_status IN ('DRAFT', 'PENDING', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED')),
    to_status   VARCHAR(20) NOT NULL CHECK (to_status IN ('DRAFT', 'PENDING', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED')),
    UNIQUE (from_status, to_status),
    CHECK (from_status <> to_status)
);

-- Reference data the app needs, not demo data. For now every change between two different statuses is allowed.
INSERT INTO status_transitions (from_status, to_status) VALUES
    ('DRAFT',       'PENDING'),  ('DRAFT',       'IN_PROGRESS'), ('DRAFT',       'RESOLVED'),    ('DRAFT',       'CANCELLED'),
    ('PENDING',     'DRAFT'),    ('PENDING',     'IN_PROGRESS'), ('PENDING',     'RESOLVED'),    ('PENDING',     'CANCELLED'),
    ('IN_PROGRESS', 'DRAFT'),    ('IN_PROGRESS', 'PENDING'),     ('IN_PROGRESS', 'RESOLVED'),    ('IN_PROGRESS', 'CANCELLED'),
    ('RESOLVED',    'DRAFT'),    ('RESOLVED',    'PENDING'),     ('RESOLVED',    'IN_PROGRESS'), ('RESOLVED',    'CANCELLED'),
    ('CANCELLED',   'DRAFT'),    ('CANCELLED',   'PENDING'),     ('CANCELLED',   'IN_PROGRESS'), ('CANCELLED',   'RESOLVED');

-- Per-year counter for order numbers (NNN/YY). OrderNumberGenerator increases it with one upsert.
CREATE TABLE order_sequences (
    seq_year      INTEGER PRIMARY KEY,
    last_sequence INTEGER NOT NULL
);

-- "order" is a reserved word in SQL, so the table is "orders".
-- Client, location and order number can be empty while the order is a DRAFT (or a cancelled draft).
CREATE TABLE orders (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number                VARCHAR(20) UNIQUE,
    branch_id                   BIGINT REFERENCES branches (id),
    client_id                   BIGINT REFERENCES clients (id),
    location_id                 BIGINT REFERENCES locations (id),
    contact_person              VARCHAR(255),
    phone                       VARCHAR(255),
    email                       VARCHAR(255),
    description                 TEXT,
    urgency                     VARCHAR(20) CHECK (urgency IN ('SAME_DAY', 'ONE_DAY', 'ONE_WEEK', 'ONE_MONTH', 'SIX_MONTHS')),
    status                      VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT', 'PENDING', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED')),
    assigned_servicer_id        BIGINT REFERENCES users (id),
    estimated_km                INTEGER,
    estimated_work_hours        NUMERIC(6, 2),
    estimated_number_of_workers INTEGER,
    estimated_material_cost     NUMERIC(10, 2),
    actual_km                   INTEGER,
    actual_work_hours           NUMERIC(6, 2),
    actual_number_of_workers    INTEGER,
    actual_material_cost        NUMERIC(10, 2),
    created_at                  TIMESTAMPTZ NOT NULL,
    updated_at                  TIMESTAMPTZ NOT NULL
);
